name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.4.4
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore:
  firebase_storage: 3.0.4
  image_picker: 0.6.0+17
  multi_image_picker: ^4.6.7
  carousel_slider: ^2.1.0
  datetime_picker_formfield: ^1.0.0
  flutter_absolute_path: ^1.0.6
  shimmer: ^1.1.1
  transparent_image: ^0.1.0
  flutter_swiper: ^1.1.6
  intl: ^0.16.1
  stripe_payment: ^1.0.6
  modal_bottom_sheet: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
